export const fruitsData = [
    {
        "id": 1,
        "name": "acai",
        "serving": "1 oz. (28.35 g)",
        "calories": "20 cal",
        "calories_100g": "70 cal",
    },
    {
        "id": 2,
        "name": "apple",
        "serving": "1 apple (182 g)	",
        "calories": "95 cal",
        "calories_100g": "52 cal",
    },
    {
        "id": 3,
        "name": "avocado",
        "serving": "1 avocado (200 g)",
        "calories": "320 cal",
        "calories_100g": "160 cal",
    },
    {
        "id": 4,
        "name": "clementine",
        "serving": "1 clementine (74 g)",
        "calories": "35 cal",
        "calories_100g": "47 cal",
    },
    {
        "id": 5,
        "name": "mango",
        "serving": "1 mango (336 g)",
        "calories": "202 cal",
        "calories_100g": "60 cal",
    },
    {
        "id": 6,
        "name": "raisins",
        "serving": "1 cup (145 g)",
        "calories": "434 cal",
        "calories_100g": "299 cal",
    },
    {
        "id": 7,
        "name": "rambutan",
        "serving": "1 rambutan (9 g)	",
        "calories": "7 cal",
        "calories_100g": "82 cal",
    },
    {
        "id": 8,
        "name": "strawberries",
        "serving": "1 cup (152 g)",
        "calories": "434 cal",
        "calories_100g": "32 cal",
    },
    {
        "id": 9,
        "name": "tangerine",
        "serving": "1 tangerine (88 g)",
        "calories": "47 cal",
        "calories_100g": "53 cal",
    },
    {
        "id": 10,
        "name": "watermelon",
        "serving": "1 wedge (286 g)",
        "calories": "86 cal",
        "calories_100g": "30 cal",
    },
  ]